### ISSUE TITLE
Question: Can you use this plugin for non-ruby projects?

### ISSUE THREAD

**Issue by JasonSmiley208** [salesforce/cucumber-metrics#28]
I am currently using Cucumber-jvm, not sure if I can use this plugin.... (investigating but if anyone can provide an answer it would be much appreciated)

**Comment by EricHartill** [comment]
@JasonSmiley208 this is a Ruby gem. I don't know how Cucumber is configured on the JVM, but I don't think this would work on that platform, even with JRuby. I may be wrong, though; if you find a way to integrate it, I'd certainly be interested in hearing about it.

**Comment by JasonSmiley208** [comment]
I know this is late, but thanks!
